version: '3'
services:
  appsurvey:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_SECURE=$VUE_APP_SECURE
        - VUE_APP_URL=$VUE_APP_URL
        - VUE_APP_PORT=$VUE_APP_PORT
    networks:
      - gateway
    ports:
      - 8080:80
    env_file:
      - .env

networks:
  gateway:
    external:
      name: gateway
