version: '3'
services:
  appsurvey:
    #build:
    #  context: .
    #  args:
    #    - VUE_APP_SECURE=$VUE_APP_SECURE
    #    - VUE_APP_URL=$VUE_APP_URL
    #    - VUE_APP_PORT=$VUE_APP_PORT
    image: registry.gitlab.com/jdsteam/crowdsource/survey-frontend:${VERSION}
    networks:
      - gateway
    ports:
      - 8080:80
    env_file:
      - .env

networks:
  gateway:
    external:
      name: gateway
